In [1]:
import numpy as np

#### all & any

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [4]:
a < 1

array([ True, False, False, False, False, False, False, False, False,
       False])

In [5]:
np.all(a < 10)

True

In [6]:
np.any(a > 5), np.any(a < 0)

(True, False)

In [7]:
np.all(a > 5), np.all(a < 10)

(False, True)

#### comparision operation

In [8]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)

In [9]:
test_a > test_b

array([False,  True, False])

In [10]:
test_a >= test_b

array([False,  True, False])

In [11]:
(test_a > test_b).any()

True

In [12]:
a = np.array([1, 3, 0], float)
a > 0

array([ True,  True, False])

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.logical_and(a > 0, a < 3)  # and 조건의 condition

array([ True, False, False])

In [16]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [17]:
c = np.array([False, True, False], bool)
c

array([False,  True, False])

In [18]:
np.logical_or(b, c)  # OR 조건의 condition

array([ True,  True,  True])

## np.where

In [19]:
a

array([1., 3., 0.])

In [20]:
np.where(a > 5)

(array([], dtype=int64),)

In [21]:
np.where(a > 5, 3, 2)  # where(condition, TRUE, FALSE)

array([2, 2, 2])

In [22]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.where(a > 10)

(array([6, 7, 8, 9]),)

In [24]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [25]:
np.isfinite(a)

array([ True, False, False])

#### argmax & argmin (array내 최대값 또는 최소값의 index를 반환함

In [26]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [44]:
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0], dtype=int64)

In [27]:
np.argmax(a), np.argmin(a)

(5, 0)

In [28]:
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [9, 76, 3, 4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [29]:
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))