In [1]:
import numpy as np

#### boolean index <-> where은 index를 뽑아내기 위한 것이고, boolean은 조건에 맞는 값을 뽑기 위함.

In [5]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [6]:
test_array

array([1., 4., 0., 2., 3., 8., 9., 7.])

In [7]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [8]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [9]:
A = np.array(
    [
        [12, 13, 14, 12, 16, 14, 11, 10, 9],
        [11, 14, 12, 15, 15, 16, 10, 12, 11],
        [10, 12, 12, 15, 14, 16, 10, 12, 12],
        [9, 11, 16, 15, 14, 16, 15, 12, 10],
        [12, 11, 16, 14, 10, 12, 16, 12, 13],
        [10, 15, 16, 14, 14, 14, 16, 15, 12],
        [13, 17, 14, 10, 14, 11, 14, 15, 10],
        [10, 16, 12, 14, 11, 12, 14, 18, 11],
        [10, 19, 12, 14, 11, 12, 14, 18, 10],
        [14, 22, 17, 19, 16, 17, 18, 17, 13],
        [10, 16, 12, 14, 11, 12, 14, 18, 11],
        [10, 16, 12, 14, 11, 12, 14, 18, 11],
        [10, 19, 12, 14, 11, 12, 14, 18, 10],
        [14, 22, 12, 14, 11, 12, 14, 17, 13],
        [10, 16, 12, 14, 11, 12, 14, 18, 11],
    ]
)
B = A < 15
B.astype(np.int)

/tmp/ipykernel_653/2678169692.py:21: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B.astype(np.int)


array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

#### fancy index

In [22]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) #반드시 integer로 선언 아무래도 index이니깐
a[b] #bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 4., 8., 6., 4.])

In [21]:
a.take(b) #take 함수: bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [18]:
a[a > 4]

array([6., 8.])

In [19]:
a.take(b)  # take 함수: bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [32]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b, c]  # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

In [33]:
a = np.array([[1, 4], [9, 16]], float)
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])